### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LUEZIS** [kegare/Cavern2#49]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  wings (wings-1.1.6-1.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  LoadingPlugin (BetterPvP_20.10.0_Forge_1.12.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.33_mc1.12.2.jar)
  ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  MistHookLoader (MistyWorld-1.12.2-1.2.4.6.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.21.12.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.14_mc1.12.2.jar)
  ratscore (rats-3.2.11-1.12.2.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-1.1.18.jar)
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.6.0-core.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 5/17/20 6:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Cavern II (cavern)
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block cakemod:caketotem, it is not an allowed value
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:59)
	at net.mcreator.cakemod.block.BlockCakeTotem$BlockCustom.func_176203_a(BlockCakeTotem.java:108)
	at cavern.client.gui.SelectListHelper.setupBlocks(SelectListHelper.java:59)
	at cavern.core.Cavern.postInit(Cavern.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

It seems like facing problem with Cakemod

**Comment by kegare** [comment]
This issue was fixed on 2.2.6 build.
